### ISSUE TITLE
Does this work with spaCy 2.0?

### ISSUE THREAD

**Issue by xumx** [kengz/spacy-nlp#11]

**Comment by kengz** [comment]
Not yet. Needs to be updated.

**Comment by Raidus** [comment]
Are you planning to update this?

Which version of spacy is working with this module? How can I install another version of spacy?

**Comment by kengz** [comment]
Yep planning to; will try to find time to do this. Currently it works with the `v1.x.x` of spacy. Give `pip install spacy==1.9.0` a try.

**Comment by Raidus** [comment]
@kengz thanks

**Comment by kengz** [comment]
fix released on npm as v1.0.9. Thanks @theThechie for the fix!
