### ISSUE TITLE
Error with Socketio-client

### ISSUE THREAD

**Issue by jeffreyflynt** [kengz/spacy-nlp#14]
I was getting the error on Ubuntu 17.10:

ERROR Traceback (most recent call last):
File "/home/xxx/.local/lib/python3.6/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
transport.recv_packet())
(STDERR) StopIteration

To fix this, I had to remove the socketIO-client and import socketIO-client-nexus for it to work.  It seems this was the cause:

socketIO-client
https://travis-ci.org/invisibleroads/socketIO-client
The library doesn't support socket.io protocol version 2.0

Hopefully this helps another that comes across this issue.

**Comment by kengz** [comment]
Fixed by #30
