### ISSUE TITLE
no module named "socketIO_client_nexus"

### ISSUE THREAD

**Issue by seeARMS** [kengz/spacy-nlp#21]
I'm getting the following error upon installation and startup:

```
File "/Users/colinarmstrong/src/memoryvue2/node_modules/spacy-nlp/src/client.py", line 13, in <module
    from socketIO_client_nexus import SocketIO, WebsocketTransport
ModuleNotFoundError: No module named 'socketIO_client_nexus'
```

Changing `socketIO_client_nexus` to `socketIO_client` fixes this.

**Comment by seeARMS** [comment]
Actually, changing to `socketIO_client` caused other issues. The actual fix is related to the install instructions: rather than `python3 -m pip install -U socketIO-client` you need to `python3 -m pip install -U socketIO-client-nexus`

**Comment by klemensz** [comment]
I created a pull request to fix this (FYI @kengz) : https://github.com/kengz/spacy-nlp/pull/30

**Comment by kengz** [comment]
Merged the PR mentioned above
