### ISSUE TITLE
How do I listen for serverPromise to let me know spacy is loaded?

### ISSUE THREAD

**Issue by ShahNewazKhan** [kengz/spacy-nlp#4]
Hi @kengz , thank you for creating this NodeJS module for Spacy!

Can you please let me know how I can use the serverPromise object to know when Spacy has been loaded? 

Currently I just timeout for 15s and then use the spacy-nlp.nlp object.

```Javascript

const spacyNLP = require('spacy-nlp')
var serverPromise = spacyNLP.server({ port: process.env.IOPORT })

serverPromise.then(function(){
    // This runs before the INFO All 1 IO clients have joined msg	
    const nlp = spacyNLP.nlp
})
```

Thanks in advance!

**Comment by kengz** [comment]
yes, you'll see that the `py` client has joined. Programmatically, try listening to the `global.ioPromise` object (provided you node instance is the same, of course). Here's [an example](https://github.com/kengz/aiva/blob/master/src/start-io.js#L87-L94) that uses this module and waits for the python IO client to join

**Comment by ShahNewazKhan** [comment]
Thanks!

**Comment by peterhuppertz** [comment]
Can you give an example how to listen to the `global.ioPromise` object? I can't get it to work. Thanks!
