### ISSUE TITLE
Spacy readiness

### ISSUE THREAD

**Issue by m0rff** [kengz/spacy-nlp#7]
`// Loading spacy may take up to 15s`

Can I determine whether spacy has finished loading?

**Comment by kengz** [comment]
yes, from the terminal log or from the promise object resolved.
Here's what some people [have tried](https://github.com/kengz/spacy-nlp/issues/5#issuecomment-296975074), though a more elegant solution is to do a wait analogous to this: [AIVA #21](https://github.com/kengz/aiva/issues/21#issuecomment-256198933)

**Comment by m0rth1um** [comment]
Would it be possible to start another spacy-nlp instance on another port. Wait for it to be ready and then kill the old one?
So I can deploy a newly trained model without downtime...

**Comment by kengz** [comment]
yes; start a new process with a different environment variable for the port called `IOPORT`. It will get picked up [here](https://github.com/kengz/spacy-nlp/blob/master/src/start-io.js#L14) and used for a started process.
